### ISSUE TITLE
Deprecation warning for `set-output` command

### ISSUE THREAD

**Issue by mishina2228** [ljharb/actions#2]
I've just found that the deprecation warning is displayed in the GitHub Actions workflows for [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import).
- https://github.com/import-js/eslint-plugin-import/actions/runs/3768297080/jobs/6406611863
  ![image](https://user-images.githubusercontent.com/32959831/209918117-4068f582-fc4e-4fda-9441-d62dbd95e944.png)
  > Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I believe the following code in this repository has something to do with it, is that right?
https://github.com/ljharb/actions/blob/d90a9d324b9dac81dc3fd2a93f98118c9db1e515/node/run/index.js#L36-L38
https://github.com/ljharb/actions/blob/6c38ef617880bbadc9f65479221121d69a51081e/node/install/index.js#L62-L64

**Comment by ljharb** [comment]
Yep, exactly right :-) i haven’t gotten around to fixing it yet because it’s not easy to test (without breaking hundreds of repos).

**Comment by ljharb** [comment]
Altho in this case the warnings are actually because i haven’t updated the github core package past .10 - for the same reason (testing and breakage)

**Comment by ljharb** [comment]
I believe 63baadd has fixed this.
