### ISSUE TITLE
node: skip non-latest odd majors

### ISSUE THREAD

**Issue by legobeat** [ljharb/actions#3]
When running with type `majors`, it doesn't seem likely that the user is interested in odd-numbered majors except current.

For example, running today with a `major` range of `>=16`, the results of deprecated v17 seems irrelevant.

@ljharb If you think this sounds reasonable I could take a stab it at

**Comment by ljharb** [comment]
On all my projects I'm definitely interested in odd majors being required; being odd or even doesn't have any bearing on the semver of what a package supports.

An enhancement I *would* like to see on node/install particularly is one that reads the `range` from `engines.node` in `package.json`, though.
