### ISSUE TITLE
Does the node workflow test the right object?

### ISSUE THREAD

**Issue by drok** [ljharb/actions#4]
I noticed that node.yml workflow, for each matrix configuration, the UUT (project) is built with the selected node version, then the test suite is run on the same node runtime. ie:

```
targets=[v1, v2, v3]
for $target in targets
   build UUT for $target
   test UUT on $target
end
```

However, in real life, a dev publishes an NPM package built with one node runtime (say v40), and when users include that package in their projects, they build their projects on their own runtime (say v33), and release the product to end users who run it on a variety or runtimes (say v1-99), ie:

```
build UUT for v40

runtimes=[v1, v2, v3]
for $runtime in runtimes
   test UUT on $runtime
end
```

Is it valid to assert that if a projects builds on version X and passes the tests on version X for any value of X, then the released package, built on version Y will run correctly on any runtime version from v1-99 ?

Shouldn't the release candidate package be tested against all the supported runtimes?

Thanks

**Comment by ljharb** [comment]
I’m not following. Most of my packages don’t have a build step, but I’ve recently added an optional “build” step that runs once, and the artifact is used on all matrix runs.

**Comment by drok** [comment]
you're right, I think... I had to remove the reusable action because it was overkill, so whatever ailed my tests is no longer an issue. Thanks

**Comment by ljharb** [comment]
Not sure why it's overkill; it can be configured to test fewer node versions if you like.
